apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment-bll
  labels:
    app: notes-app-bll
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app-bll
  template:
    metadata:
      labels:
        app: notes-app-bll
    spec:
      containers:
      - name: notes-app-bll
        image: 471112967512.dkr.ecr.us-east-1.amazonaws.com/notes-app-bll:latest
        resources:
          requests:
            cpu: "300m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000