name: Publish Docker image to Amazon ECR and deploy to Amazon EKS

on:
  push:
    tags:
      - 'V*'
    
  workflow_dispatch: 

jobs:
  deploy: 
    name: Build image and deploy to Amazon ECR
    runs-on: ubuntu-latest
      
    steps:
      - name: Repository checkout 
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: npm install 

      - name: Run test
        run: npm test

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build and push of Docker image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG